using System;
using Simplic.Boilerplate.Shared;
using Simplic.Framework.WebAPI.Core;
using Simplic.Boilerplate;
using System.Threading.Tasks;
using System.Web.Http;
using Swashbuckle.Swagger.Annotations;
using Unity;

namespace Simplic.PlugIn.Boilerplate.Server
{
    // TODO: We some role management here. Each role per Endpoint? Or Endpoint group?

    /// <summary>
    /// Controller for the contact api.
    /// </summary>
    [Framework.WebAPI.JWTAuthorize]
    public class ContactController : ExtendedApiController
    {
        private readonly IContactService contactService;
        private readonly AutoMapper.IMapper mapper;

        /// <summary>
        /// Initializes a new instance of the contact controller.
        /// </summary>
        /// <param name="contactService">Contact service.</param>
        /// <param name="mapper">Mapper.</param>
        public ContactController(IContactService contactService, [Dependency("BoilerplateMapper")] AutoMapper.IMapper mapper)
        {
            this.contactService = contactService;
            this.mapper = mapper;
        }

        /// <summary>
        /// Asynchronously retrieves the contact.
        /// </summary>
        /// <param name="id">Identifier of the contact.</param>
        /// <returns>Task of <see cref="IHttpActionResult"/>.</returns>
        [HttpGet]
        [SwaggerResponse(System.Net.HttpStatusCode.OK, "Returns a contact instance by id", typeof(ContactModel))]
        [SwaggerResponse(System.Net.HttpStatusCode.BadRequest, "Returns a message if the contact could not be found using the given id", typeof(string))]
        [SwaggerResponse(System.Net.HttpStatusCode.InternalServerError, "If retrieving fails due to a technical reason", typeof(Exception))]
        public async Task<IHttpActionResult> GetAsync(Guid id)
        {
            try
            {
                var contact = await contactService.GetAsync(id);

                if (contact == null)
                    return BadRequest($"Coult not find resource by id {id}");

                // Return updated contact
                return Ok(mapper.Map<ContactModel>(contact));
            }
            catch (Exception ex)
            {
                // Information hiding, what is good to return and what is bad?
                return InternalServerError(ex);
            }
        }

        /// <summary>
        /// Asynchronously creates the contact.
        /// </summary>
        /// <param name="model">Model of the contact.</param>
        /// <returns>Task of <see cref="IHttpActionResult"/>.</returns>
        [HttpPost]
        [SwaggerResponse(System.Net.HttpStatusCode.OK, "Create a new contact instance and returns the created contact", typeof(ContactModel))]
        [SwaggerResponse(System.Net.HttpStatusCode.InternalServerError, "If creating fails due to a technical reason", typeof(Exception))]
        public async Task<IHttpActionResult> CreateAsync(CreateContactRequest model)
        {
            var contact = mapper.Map<Contact>(model);
            // The id should be generated by the server
            contact.Id = Guid.NewGuid();

            try
            {
                await contactService.CreateAsync(contact);
            }
            catch (Exception ex)
            {
                // Information hiding, what is good to return and what is bad?
                return InternalServerError(ex);
            }

            // Return updated contact
            return Ok(mapper.Map<ContactModel>(contact));
        }

        /// <summary>
        /// Asynchronously updates the contact.
        /// </summary>
        /// <param name="model">Model of the contact.</param>
        /// <returns>Task of <see cref="IHttpActionResult"/>.</returns>
        [HttpPut]
        [SwaggerResponse(System.Net.HttpStatusCode.OK, "Updates an exusting contact instance and returns the created contact", typeof(ContactModel))]
        [SwaggerResponse(System.Net.HttpStatusCode.InternalServerError, "If updating fails due to a technical reason", typeof(Exception))]
        public async Task<IHttpActionResult> UpdateAsync(UpdateContactRequest model)
        {
            var contact = mapper.Map<Contact>(model);

            try
            {
                await contactService.UpdateAsync(contact);
            }
            catch (Exception ex)
            {
                // Information hiding, what is good to return and what is bad?
                return InternalServerError(ex);
            }

            // Return updated contact
            return Ok(mapper.Map<ContactModel>(contact));
        }

        /// <summary>
        /// Asynchronously deletes the contact.
        /// </summary>
        /// <param name="id">Identifier of the contact.</param>
        /// <returns>Task of <see cref="IHttpActionResult"/>.</returns>
        [HttpDelete]
        [SwaggerResponse(System.Net.HttpStatusCode.OK, "Deletes an existing contact", typeof(DeleteContactResponse))]
        [SwaggerResponse(System.Net.HttpStatusCode.InternalServerError, "If deleting fails due to a technical reason", typeof(Exception))]
        public async Task<IHttpActionResult> DeleteAsync(Guid id)
        {
            try
            {
                // Check whether deleting is allowed
                await contactService.DeleteAsync(id);
            }
            catch (Exception ex)
            {
                // Information hiding, what is good to return and what is bad?
                return InternalServerError(ex);
            }

            return Ok(new DeleteContactResponse { Id = id, Success = true });
        }
    }
}
